### ISSUE TITLE
Schema Violation: No `ValueType` defined in Qualifiers in multiple Submodels

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/submodel-templates#10]
According to the specification, `ValueType` is a mandatory attribute. However, we have noticed that `ValueType` is missing in the published AASX files for templates that have qualifiers. This issue occurs in several submodels, including `Digital Nameplate`, `Contact Information`, `Handover Documentation`, `Provision of Simulation Models`, `Technical Data`, and `Time Series Data`.

**Comment by SAidta** [comment]
@Rudra-sandeep please check the issue.

**Comment by Rudra-sandeep** [comment]
@zrgt Please check the latest versions of the SMT's this issue is been resolved

[https://github.com/admin-shell-io/submodel-templates/tree/main/published](url)
