### ISSUE TITLE
Nameplate example swapped content

### ISSUE THREAD

**Issue by felix-schubert** [admin-shell-io/submodel-templates#11]
Sample_ZVEI_Digital_Nameplate_V10/aasx/https___example_com_ids_aas_9370_1290_3012_2294/https___example_com_ids_aas_9370_1290_3012_2294.aas.xml
The IEC:definition is swapped for these descriptions:

<aas:conceptDescription>
<aas:idShort/>
<aas:identification idType="IRI">https://admin-shell.io/zvei/nameplate/1/0/Nameplate/AssetSpecificProperties</aas:identification>

<IEC:definition>
<IEC:langString lang="en">Collection of guideline-specific properties</IEC:langString>
<IEC:langString lang="de">Sammlung der Richtlinien-spezifischen Merkmale</IEC:langString>

**is swapped with**

<aas:conceptDescription>
<aas:idShort/>
<aas:identification idType="IRI">https://admin-shell.io/zvei/nameplate/1/0/Nameplate/AssetSpecificProperties/GuidelineSpecificProperties</aas:identification>

<IEC:definition>
<IEC:langString lang="en">Asset specific nameplate information required by guideline, stipulation or legislation</IEC:langString>
<IEC:langString lang="de">Asset-spezifische Typenschildinformation, die von weiteren Normen, Standards und Richtlinien gefordert wird</IEC:langString>

**Comment by Rudra-sandeep** [comment]
We have already updated the SMT, please check into the newest version of respective SMT.
