### ISSUE TITLE
Suspicious space in an "id" in ContactInformation

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/submodel-templates#18]
There is a suspicious "space" character in `ContactInformation.IPCommunication.TypeOfCommunication.id`:

`https://admin-shell.io/zvei/nameplate/1/0/ ContactInformations/ContactInformation/IPCommunication/TypeOfCommunication`

![image](https://user-images.githubusercontent.com/1770684/219011799-cc537f70-f75f-4b4e-ba4b-032e575dc69f.png)

In all other places that use the is base `https://admin-shell.io/zvei/nameplate/1/0/` there is no space.

**Comment by Rudra-sandeep** [comment]
@shuebner Please check the latest version of the SMT the issue is resolved
