### ISSUE TITLE
ContactInformation should not use "example.com" id

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/submodel-templates#21]
ContactInformation V1.0 has an id of `https://example.com/ids/sm/1231_6162_1022_9579`
![image](https://user-images.githubusercontent.com/1770684/219310804-feacdd33-2907-44f1-9ba5-348baf38818d.png)

Why would a standardized submodel template be published with "example" in its id?

This is suspicious and inconsistent with e. g. TechnicalData V1.2, which has a more appropriate id `https://admin-shell.io/ZVEI/TechnicalData/Submodel/1/2`.

**Comment by Rudra-sandeep** [comment]
@shuebner Please check the latest version of SMT the problem is solved
