### ISSUE TITLE
TechnicalData V1.2 contains semanticId with trailing space

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/submodel-templates#22]
TechnicalData V1.2 --> GeneralInformation --> ManufacturerProductDesignation has semanticId/value of `0173-1#02-AAW338#001 ` (including the trailing space).

![image](https://user-images.githubusercontent.com/1770684/219319299-c862f026-e402-420e-94d2-294884045e85.png)

This seems to be wrong.
All `id` values everywhere should be trimmed.

**Comment by Rudra-sandeep** [comment]
@shuebner Please check the latest version of the SMT the issue is resolved
