### ISSUE TITLE
Unclear ValueOnly serialization of Language property in ContactInformation 1.0

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/submodel-templates#24]
The submodel element `Language` is defined as `Property` with a Multiplicity qualifier `ZeroToOne`.
It is unclear what this is supposed to mean for the ValueOnly serialization (see [Details of the Asset AdministrationShell Part 2](https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2021/11/Details_of_the_Asset_Administration_Shell_Part_2_V1.pdf), chapter 9.4.2, page 81)

Please specify.

**Comment by BirgitBoss** [comment]
Language is this context seems to be a "normal" submodel element "Property". So your question is how to deal with optional elements in ValuOnly serialization in general?

**Comment by shuebner** [comment]
Sorry for the late reply. I moved on to a different project. It has been half a year since I created the issue. I no longer have the context in mind.
