### ISSUE TITLE
Violation of Constraint AASd-002 in multiple templates

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/submodel-templates#26]
Constraint AASd-002: idShort of Referables shall only feature letters, digits, underscore ("_"); starting mandatory with a letter. I.e. [a-zA-Z][a-zA-Z0-9_]+

In multiple submodel-templates the Constraint AASd-002 is violated by `SubmodelElements` in `SubmodelElementCollection`-objects. Normally people wanna show with `{00}`, that the collection is actuallly a list and idShorts will be iterated in `SubmodelElementCollection`. E.g. `IPCommunication{00}` in the submodel-template "Digital Nameplate".

**Comment by jh-isw** [comment]
This may help:

> If an idShort ends with '{00}', this indicates a suffix of the respective length (here: 2) of decimal digits, in order to make the idShort unique. A different idShort might be choosen, as long as it is unique in the parent's context.

from _GUIDELINE: HOW TO CREATE A SUBMODEL TEMPLATE SPECIFICATION_ found on IDTA's website.

**Comment by zrgt** [comment]
@jh-isw thank you for the referenced explanation, but `{00}` still does not comply with the specified constraint. The constraint description does not include any mention of exceptions, causing many developers to view `{00}` as a violation unless they have read the referenced guideline. Consequently, some SDKs, where constraints are implemented, throw exceptions when attempting to read such a template.

To address this issue, I see two potential solutions:
- Modify the constraint description to include an exception clause.
- Replace `{00}` with `_00`.

**Comment by BirgitBoss** [comment]
We discussed whether to relax the constraints for Submodel Templates (Submodel with kin=Template) or whether to change the way to denote such wildcards. 
The decision was to change the "How to create a SMT", the new version will be published soon.
Additionally, most SMT with such constraints violations need to consider to use SubmodelElementList.

**Comment by MichaelHoffmeisterFesto** [comment]
Hello,
please see: "IDTA GUIDELINE -- HOW TO CREATE A SUBMODEL TEMPLATE SPECIFICATION".
In this document (in review) we already said, we will replace "{00}" with "__00__". This is also already in the tool chain.
Therefore, I consider this solved.
