### ISSUE TITLE
Handover Documentation 1.2 idShort with {00} suffix really needed?

### ISSUE THREAD

**Issue by hmrc87** [admin-shell-io/submodel-templates#31]
On page 13 it states:

![image](https://github.com/admin-shell-io/submodel-templates/assets/1226017/974a84c4-1957-4249-8827-85e950b74c73)

Does it make sense to have multiple Handover Documentation Submodels within a Shell or is it a typo?

**Comment by Rudra-sandeep** [comment]
@hmrc87 The {00} suffix is used to ensure that idShort values are unique within the context of their parent SubmodelElement.
