### ISSUE TITLE
HandoverDocumentation 1.2 RefersTo external Document

### ISSUE THREAD

**Issue by hmrc87** [admin-shell-io/submodel-templates#33]
![image](https://github.com/admin-shell-io/submodel-templates/assets/1226017/be7c7977-ea83-4401-9977-27b02a6df8a1)

Hi, is it possible to refer to a document that resides in another shell? An example would be an instance shell that refers to its documentation on its type shell.

**Comment by Rudra-sandeep** [comment]
@hmrc87 Yes, it is possible to refer to a document that resides in another shell. The " Submodel Handover Documentation" specification supports this capability through the use of ReferenceElement, specifically the RefersTo element. This allows an instance shell to reference documentation located in its type shell or any other shell.
