### ISSUE TITLE
 Submission of submodels in "yellow_pages"

### ISSUE THREAD

**Issue by gart-labor** [admin-shell-io/submodel-templates#34]
Hello, 

What is the process for publishing submodels in the IDTA GitHub folder "Yellow_Pages"? 

In 2018, we developed submodels (~ 20) for lifecycle of assets/pumps with VDMA working groups. Many of the contents coincide with contents that have been published by IDTA in the meantime (Digital nameplate, Maintenance, ...). We would like to publish the submodels whose contents are not yet covered by the published IDTA submodels in the "Yellow_Pages". 

Greetings from Cologne, 
Björn

**Comment by SAidta** [comment]
Hello Björn,

Thank you for your interest in developing submodels for the IDTA. We have a defined process in place for this purpose. To share your submodel ideas, you can visit the following link: https://industrialdigitaltwin.org/en/content-hub/create-a-submodel.

Once you submit your submodel idea through the provided link, our team will review it and get in touch with you as soon as possible. We appreciate your contribution and look forward to collaborating with you.

Best regards,
