### ISSUE TITLE
Generic Frame for Technical Data for Industrial Equipment in Manufacturing (Version 1.2): mismatch ManufacturerPartNumer/ManufacturerArticleNumber

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/submodel-templates#36]
Sometimes idShort ManufacturerPartNumer and sometimes idShort ManufacturerArticleNumber ist used in same document. 

SMT Template (aasx file) uses ManufacturerArticleNumber. 
AASX-PE Add-In Technical data (sheet) model (v.1.1) uses ManufacturerPartNumber.

**Comment by Rudra-sandeep** [comment]
@foprs Please check the latest version of the SMT  the issue is resolved 
https://github.com/admin-shell-io/submodel-templates/tree/main/published/Technical_Data/1/2
