### ISSUE TITLE
Template "02015 Control Component Type" Submodel Semantic ID missing

### ISSUE THREAD

**Issue by Hilscher-TKratz** [admin-shell-io/submodel-templates#41]
As stated in the title, the semantic ID for the "Submodel Control Component Type" is missing in the currently provided template.

Per specification (chapter 2.2, table 1) it has to be...
[IRI] https://admin-shell.io/idta/ControlComponent/Type/1/0

**Comment by danielporta** [comment]
Thanks for the finding! In the V2-AASX Package Explorer the Semantic Id is shown. However, the type is not properly specified. We will take care of that.

**Comment by Rudra-sandeep** [comment]
@Hilscher-TKratz Please check the latest version of the SMT the issue is resolved
