### ISSUE TITLE
Template "02007 Software Nameplate" Submodel Semantic ID missing

### ISSUE THREAD

**Issue by Hilscher-TKratz** [admin-shell-io/submodel-templates#42]
As stated in the title, the semantic ID for the Submodel "Software Nameplate" is missing in the currently provided template.

Per specification (chapter 2.1, table 1) it has to be...
[IRI] https://admin-shell.io/idta/SoftwareNameplate/1/0

Currently this information is provided as SubmodelReference and Submodel-ID, which does not seem to be correct.

**Comment by SAidta** [comment]
rechecked semanticID is available.
![image](https://github.com/admin-shell-io/submodel-templates/assets/93717810/7c993073-ef87-4788-b64c-e863b6070218)

**Comment by Hilscher-TKratz** [comment]
But it's not used in the Semantic-ID field, but in the generic ID field (which turns, depending on the context, to Submodel-ID / AAS-ID / Concept Description-ID...)

![image](https://github.com/admin-shell-io/submodel-templates/assets/127853587/d2cf945b-3b40-455d-84ca-2d95c3c5eb0d)

It just does not seem correct, that's why I basically hinted to it.

**Comment by SAidta** [comment]
This issue will be forwarded to the corresponding working group.

**Comment by Rudra-sandeep** [comment]
@Hilscher-TKratz Please check the latest version of the SMT the issue is resolved
