### ISSUE TITLE
Question of handling Quality attribute of OPC data [QUESTION]

### ISSUE THREAD

**Issue by STUBA-rupr** [admin-shell-io/submodel-templates#43]
I am trying to implement a service which will return historical data as Time Series JSON string.
A a source I have InFlux database which is filled by OPC UA data.
The influx query like:
```
            var flux = @"from(bucket:""PLCSIMTest"") 
                |> range(start: -2d)
                |> filter(fn: (r) => r[""id""] == ""ns=4;i=3"" or r[""id""] == ""ns=4;i=5"" )
                 |> sample(n: 5, pos: 1)  
                ";
```
returns data as:

- the table[1] is the node ns=4;i=3 
![image](https://github.com/admin-shell-io/submodel-templates/assets/55546830/a89635fe-f772-4074-8935-b840e9d481af)

- table[0] is the node ns=4;i=5 
![image](https://github.com/admin-shell-io/submodel-templates/assets/55546830/f272705f-8e83-462d-9e63-7d518e60e0b4)

- table[2] contains Quality attribute of ns=4;i=3 value
![image](https://github.com/admin-shell-io/submodel-templates/assets/55546830/eff67d54-1b15-4240-9e17-bf174c89b10a)

- table[3] contains Quality attribute of ns=4;i=5 value
![image](https://github.com/admin-shell-io/submodel-templates/assets/55546830/bb47c3ec-4534-4e04-85c6-2ae219ff3986)

How can I describe these data in Metadata SM, once it suppose to have just one record?
![image](https://github.com/admin-shell-io/submodel-templates/assets/55546830/e0c335b2-54fe-4c9e-a567-6b3ba235b0b4)

Thank you
Rudo

**Comment by Rudra-sandeep** [comment]
@STUBA-rupr You can define multiple properties under the record SMC .

For example

{
    "idShort": "TimeSeries",
    "semanticId": "https://admin-shell.io/idta/TimeSeries/1/1",
    "submodelElements": [
        {
            "idShort": "Metadata",
            "semanticId": "https://admin-shell.io/idta/TimeSeries/Metadata/1/1",
            "submodelElementCollections": [
                {
                    "idShort": "Record",
                    "semanticId": "https://admin-shell.io/idta/TimeSeries/Record/1/1",
                    "properties": [
                        {
                            "idShort": "Time",
                            "semanticId": "https://admin-shell.io/idta/TimeSeries/UtcTime/1/1",
                            "valueType": "TIMESTAMP",
                            "value": "2020-09-19T14:40:38.318Z"
                        },
                        {
                            "idShort": "Value",
                            "semanticId": "custom:semanticId:forValue",
                            "valueType": "double",
                            "value": 23.415
                        },
                        {
                            "idShort": "Quality",
                            "semanticId": "https://admin-shell.io/idta/TimeSeries/Qualifier/ValueQualityQualifier/1/1",
                            "valueType": "string",
                            "value": "good"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by STUBA-rupr** [comment]
[like]  Rudolf Pribiš reacted to your message:
________________________________
