### ISSUE TITLE
Question about Battery Data Template

### ISSUE THREAD

**Issue by b3n3d17** [admin-shell-io/submodel-templates#44]
I have seen on the website https://industrialdigitaltwin.org/content-hub/teilmodelle that a **Battery Data Template** is under development.

![Screenshot](https://github.com/admin-shell-io/submodel-templates/assets/30891577/a830bb16-3b8b-4e0f-8e57-d6a4ac0f0a2e)

Does anyone here have any "draft" of this template and know anything about the timeline when this will be published?

I would have expected a draft to be in this repository under the development folder.

Greetings
Benedikt

**Comment by seicke-harting** [comment]
Dear Benedikt,

the KickOff meeting for the submodel "Battery Data Template"  took place just last Thursday, 2023-10-12.
Accordingly, there is no draft yet.

Best regards
Sebastian

**Comment by b3n3d17** [comment]
Hi Sebastian,

thank you for the quick answer.
It this repository the place where the draft will be worked on and first published, or is there a mailinglist to see the ongoing development?

Greetings
Benedikt

**Comment by seicke-harting** [comment]
@SAidta: Maybe you can help?

**Comment by b3n3d17** [comment]
@SAidta is there any update?

**Comment by sebastiankb** [comment]
Hi Benedikt,

@SAidta is currently on vacation. Maybe I can try to answer your question: usually, the IDTA develops the documents within Teams groups. After finalization, the documents are published like here on github. The working group meetings take place every 2 weeks. If you are interested in joining, please send me a private message.

BR
Sebastian (another one ;-))

**Comment by b3n3d17** [comment]
Hi (other) Sebastian ;),

thank you for the information.
Ill send you a pm.

Greetings and thanks Sebastian^2
Benedikt
