### ISSUE TITLE
Submodel Capability

### ISSUE THREAD

**Issue by miriamschleipenEKS** [admin-shell-io/submodel-templates#49]
I am not able to open the submodel capability (https://github.com/admin-shell-io/submodel-templates/blob/main/development/Capability/1/0/CapabilitySubModelTemplate_V1.3.aasx) in AASXPackageExplorer https://github.com/admin-shell-io/aasx-package-explorer/releases/tag/v2023-09-12.alpha. (Error: Object reference not set to an instance of an object.). The aasx file content may be exported to XML and reviewed manually. Is it not possible to open the file directly in AASXPackageExplorer? Other Submodel Templates may be opened without any problem.

**Comment by Rudra-sandeep** [comment]
@miriamschleipenEKS Please try to open it with newest version of Package Explorer and also the  newest version of SMT Capability which you can find in our Repo
