### ISSUE TITLE
Use Case Template

### ISSUE THREAD

**Issue by sebastiankb** [admin-shell-io/submodel-templates#5]
Please provide the following information on your use case description as a new github issue. 

- Submitter(s)
- Target Users (e.g., supplier, integrator, costumer)
- Description (detail description of use case; requirements; if possible use images/diagrams etc)
- Gaps (e.g., what is missing so far, what is needed)
- Links (e.g., references to related works, existing standards, link to a presentation etc)

**Comment by SAidta** [comment]
The use case was discussed within the working group.
