### ISSUE TITLE
SoftwareNameplate v1.0 has wrong example data for xs:date

### ISSUE THREAD

**Issue by lenaxus** [admin-shell-io/submodel-templates#52]
In the SoftwareNameplate submodel are three properties defined with the type "xs:date" (InstallationDate, BuildDate, ReleaseDate). For that properties are example values declared in the submodel template. For ReleaseDate is this e.g. `20220207`.

When I validated my SoftwareNameplate submodel which was created out of the here published template [with this official validation tool](https://github.com/admin-shell-io/aas-test-engines), I got an error when specifying the ReleaseDate in that format. I checked again the specification of the Metamodel Version3 and found out, that the right value for an xs:date is `2022-02-07`. With that value the validation tool also said that my submodel is valid. 

Can you please check why the example value is in that format in the submodel specification?

**Comment by Rudra-sandeep** [comment]
@lenaxus Please check the latest version of the SMT the issue is resolved
