### ISSUE TITLE
TimeSeriesData: Illegal embeddedDataSpecification snippet

### ISSUE THREAD

**Issue by geso02** [admin-shell-io/submodel-templates#53]
At line 155 of the inner aasx-xml file of the [time-series-template](https://github.com/admin-shell-io/submodel-templates/blob/main/published/Time%20Series%20Data/1/1/IDTA%2002008-1-1_Template_TimeSeriesData.aasx) there is this embeddedDataSpecification block:

``` xml
<aas:embeddedDataSpecification>
  <aas:dataSpecification>
  <aas:keys />
</aas:dataSpecification>
```

We used the time series template and it was possible to open the Submodel with AasPackageExplorer V2 but when we opened it with v3 and clicked on it nothing was displayed. Seems as the UI crashes during view-creation.

We removed this block and it was possible to see it also in V3. All other embeddedDataSpecifications there set. Just this one needs to be fixed.

**Comment by juileetikekar** [comment]
Hi @geso02,

Please use the latest version of the AASPE, which fixes the empty lists issue.

Please refer my comment https://github.com/admin-shell-io/submodel-templates/issues/45#issuecomment-2024620016 for more details.
