### ISSUE TITLE
SMT Carbon Footprint - Error in Semantic IDs in sample AASX file

### ISSUE THREAD

**Issue by MMuellerMitsubishi** [admin-shell-io/submodel-templates#56]
There are a few errors/typo in the semantic IDs for some properterties in the AASX file of the SMT Carbon Footprint.

For TCFCalculationMethod the semantic ID of the property is 0173-1#02-ABG859#001
but the ID of the Concept Description has #002 as ending

Same happened for: TCFReferenceValueForCalculation and TCFProcessesForGreenhouseGasEmissionInATransportService

![image](https://github.com/admin-shell-io/submodel-templates/assets/81679020/be4a6832-19bb-4159-a913-e71b839385f4)

**Comment by Rudra-sandeep** [comment]
@MMuellerMitsubishi Please refer to the latest version of SMT
[https://github.com/admin-shell-io/submodel-templates/blob/main/published/Carbon%20Footprint/0/9/IDTA%202023-0-9%20_Template_CarbonFootprint.aasx](url)
