### ISSUE TITLE
Direct references to external AAS or Submodels using ReferenceElements or RelationshipElements.

### ISSUE THREAD

**Issue by griemens** [admin-shell-io/submodel-templates#57]
At official FAQs. It states for refencing external sub models 

"2. Direct references to external AAS or Submodels using ReferenceElements or RelationshipElements. We currently do not recommend this method in case of lacking generalizability and creation of tight couplings between AAS (by taking over the “resolution” part).)"
[https://github.com/admin-shell-io/questions-and-answers#id42](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadmin-shell-io%2Fquestions-and-answers%23id42&data=05%7C02%7Cgert.de_nul%40siemens.com%7C70cf6acc62c34dc0170808dc58822415%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638482563169230360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=vZN1%2BCCiNq%2BPu6eFw4XpgNLe60s81hGIGA7gmC7gRvQ%3D&reserved=0)
[https://admin-shell-io.github.io/questions-and-answers/#id42](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fadmin-shell-io.github.io%2Fquestions-and-answers%2F%23id42&data=05%7C02%7Cgert.de_nul%40siemens.com%7C70cf6acc62c34dc0170808dc58822415%7C38ae3bcd95794fd4addab42e1495d55a%7C1%7C0%7C638482563169246793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ZUTpSTTbMNUTL9RU8acLYIg0pgXwGjP5OTZFxaTQbLc%3D&reserved=0)

Is this today still not recommended ?

Thank you for the insight.

**Comment by BirgitBoss** [comment]
Which use case do you have in mind  that would benefit from this kind of direct referencing? In most cases it is better to do the coupling via assetId and SemanticId.

**Comment by BirgitBoss** [comment]
I am closing the issue. Please feel free to reopen the issue if you feel the answer is not satisfying.
