### ISSUE TITLE
Asset Data Integration

### ISSUE THREAD

**Issue by magnus-redeker** [admin-shell-io/submodel-templates#6]
**Submitter:** 
Magnus Redeker (Fraunhofer IOSB-INA)

**Target Users:** 
1. Machine Operator
2. Factory Manager
3. Data Scientist
4. Autnomous Dashboard Generation System
5. Digital Twin
6. etc.

**Description:**
1. The Target User connects to the AAS of the Asset of interest 
2. The Target User connects to the Asset Interface Description Submodel describing which data (semanticId) in which quality (semanticId) the Asset provides through which interfaces with which security requirements
3. The Target User selects relevant data points in relevant Asset interfaces
4. The Target User configures one client per relevant Asset interface fullfilling the security requirements and configuring a mapping of the selected Asset data into a data sink
-for example: 
--Asset Interface Description: MQTT-topic, payload and security
--data sink: submodel elements like properties, blobs, etc. in an AAS
5. The Target User deploys the configured clients that connect to the Asset interfaces and integrate data into the specified data sinks

**Technologies of interest:**
1. HTTPS/REST
2. MQTT 
3. Apache Kafka
4. OPC UA: Standard, PubSub, ReverseConnect
5. ProfiBus
6. ProfiNet
7. ModBus
8. InfluxDB
9. MongoDB
10. MinIO
11. etc.

**Gaps:**
Currently, no "omniscient" register like the Asset Interface Description exists

**Links:**
None

**Comment by SAidta** [comment]
The use case was discussed within the working group.
