### ISSUE TITLE
Wrong DataSpecification ID in various SMT

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/submodel-templates#60]
In various SMT, e.g. Time Series Data, a wrong DataSpecification ID is taken: http://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360/3/0 instead of
http://admin-shell.io/DataSpecificationTemplates/DataSpecificationIec61360/3/0 (IEC -> Iec)

This prevents the API due to the "oneOf" restriction for Data Specifications to load the CD.

**Comment by Rudra-sandeep** [comment]
@foprs Please refer to below linked issues for this issue

[https://github.com/eclipse-aaspe/package-explorer/issues/196#issuecomment-2106346210](url)
[https://github.com/admin-shell-io/aas-specs-iec61360/issues/2#issuecomment-1864303829](url)

**Comment by Rudra-sandeep** [comment]
@foprs Thank you for raising the issue and the issue is been solved you can find the Bugfixed SMT at below link
[https://github.com/admin-shell-io/submodel-templates](url)
