### ISSUE TITLE
Documentation of SML with SMC as child in Submodel Template (SMT) specifications

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/submodel-templates#65]
There is the constraint AASd-120 in the metamodel specification stating that "_idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified_".

![image](https://github.com/admin-shell-io/submodel-templates/assets/118162568/9e063df5-85c8-479b-994d-cfcee728d9e8)

However in some SMT specifications like IDTA 02036-1-0 Product Change Notifications (Draft) an idShort is awarded and a separate class table is used to document the elements of the SMC. See the picture below.

![image](https://github.com/admin-shell-io/submodel-templates/assets/118162568/651f7579-cffc-4c41-8343-e8b6fcff4c7f)

**My question is whether contraint AASd-120 is effective for SMT and whether the existing SMT specifications with idShort are valid or not.**

**Comment by BirgitBoss** [comment]
We need a different kind of table for SubmodelElementList, e.g.

![image](https://github.com/admin-shell-io/submodel-templates/assets/59824205/ac8440d3-056e-414c-af80-ababb8a05046)

**Comment by foprs** [comment]
With the constraint AASd-120 in the metamodel specification stating that "idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified" there is in the example above no idShort available for the SubmodelElementCollection.

In the screenshot above there is a class name "Marking" defined in the specification document. This class name is not modeled in the AASX.

The SubmodelElementCollection with class name "Marking" would need a separate class table for its elements where no idShort would be available for (if constraint AASd-120 applies). 

Question: Should the line idShort be replaced by "Class name" in this case for the standard table for SMC?

**Comment by BirgitBoss** [comment]
The SMC table for Marking would be part of the SMT specification and is used by the SML. But you are right, it would not be part of the aasx file itself. There we only have the semanticId for referencing.

I would still use the idShort Marking for the SMC table as well. It is some kind of SMT dropin that could also be reused at other places different to the SML Markings.

What could be done today with V3.0: create a ConceptDescription for the semanticIdListElement and define Marking as the idShort of  the ConceptDescription.

**Comment by BirgitBoss** [comment]
But perhaps we should relax constraint AASd-120  for SMT.

**Comment by BirgitBoss** [comment]
I will close this issue, please feel free to reopen it if the steps taken are not considered to be sufficient. Thank you, Birgit
