### ISSUE TITLE
Template_HierarchicalStructuresEnablingBoM not opening in AASX Package Explorer

### ISSUE THREAD

**Issue by NLIFTTUW** [admin-shell-io/submodel-templates#66]
No Problems opening any other Templates using Package Explorer V3.0 either via File/Open/... or Drag&Drop other than with the HierarchialStructures Template

> Error: while receiving file drop to window: PackageCentral: while performing load from C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first) PackageCentral: while performing load from C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first)
InnerException: One or more errors occurred. (While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first)
InnerException: While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 102
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 376
   at AasxPackageExplorer.MainWindow.Window_Drop(Object sender, DragEventArgs e) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 3364.Inner message: One or more errors occurred. (While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first)
Inner message: While opening aasx C:\Users\User\AppData\Local\Temp\tmp6F77.aasx from source local file: C:\Users\User\Desktop\Asset Administration Shell\Templates\Bill Of Materials\IDTA 02011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx buffered to: C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 491 gave: While reading the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \AdminShellPackageEnv.cs:line 481 gave: While reading spec from the AASX C:\Users\User\AppData\Local\Temp\tmp6F77.aasx at \xmlization.cs:line 20625 gave: The required property Type has not been given in the XML representation of an instance of class Reference at: submodels/*[0]/submodelElements/*[0]/statements/*[0]/statements/*[1]/first

**Comment by Rudra-sandeep** [comment]
@NLIFTTUW Please try to open it with the latest version of the AASPE

**Comment by Rudra-sandeep** [comment]
@NLIFTTUW The issue is resolved please refer to below link for the SMT

[https://github.com/admin-shell-io/submodel-templates/blob/main/published/Hierarchical%20Structures%20enabling%20Bills%20of%20Material/1/0/IDTA%2002011-1-0_Template_HierarchicalStructuresEnablingBoM.aasx](url)

**Comment by NLIFTTUW** [comment]
Thank you very much
