### ISSUE TITLE
Multiple Constraint Violations in Time-Series Data Submodel

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/submodel-templates#67]
I encountered several constraint violations when attempting to open the Time-Series Data Submodel template:

- The `dataSpecification` mandatory attribute is missing in multiple `embeddedDataSpecification`s.
- Several `shortName`s of `dataSpecificationIec61360` exceed the length limit of 18 characters.
- Some mandatory `shortName`s of `dataSpecificationIec61360` are not set.

**Comment by Rudra-sandeep** [comment]
@zrgt Please use the latest JSON file of the respective SMT which as been uploaded yesterday

**Comment by zrgt** [comment]
@Rudra-sandeep the JSON has still problems:
- Properties with different `valueType`s have a `value`='' which is not None, it is string. In cases where `valueType` is not string it causes errors. 
Now:
```json
                {
                  "category": "VARIABLE",
                  "idShort": "RecordCount",
                  "semanticId": {
                    "type": "ExternalReference",
                    "keys": [
                      {
                        "type": "GlobalReference",
                        "value": "https://admin-shell.io/idta/TimeSeries/Segment/RecordCount/1/1"
                      }
                    ]
                  },
                  "qualifiers": [
                    {
                      "type": "Cardinality",
                      "valueType": "xs:string",
                      "value": "ZeroToOne"
                    }
                  ],
                  "valueType": "xs:long",
                  "value": "",
                  "modelType": "Property"
                }
```

Should be:
```json
                {
                  "category": "VARIABLE",
                  "idShort": "RecordCount",
                  "semanticId": {
                    "type": "ExternalReference",
                    "keys": [
                      {
                        "type": "GlobalReference",
                        "value": "https://admin-shell.io/idta/TimeSeries/Segment/RecordCount/1/1"
                      }
                    ]
                  },
                  "qualifiers": [
                    {
                      "type": "Cardinality",
                      "valueType": "xs:string",
                      "value": "ZeroToOne"
                    }
                  ],
                  "valueType": "xs:long",
                  "modelType": "Property"
                }
```

- Also in cases where `valueType` is string and value is not set the `value` key should be just removed from property object.
- File object also has an empty string as a value: `"value": ""`. This also should be removed.



Tested with https://github.com/rwth-iat/aas-compliance-tool

**Comment by zrgt** [comment]
The problem also occures in `Range` object, as it has `min` and `max` values which should be removed or set to valid XSD datetime string
```json
{
                "idShort": "Timespan",
                "description": [
                  {
                    "language": "en",
                    "text": "The valueType of the given timespan must match the valueType of the time properties of the segments."
                  }
                ],
                "semanticId": {
                  "type": "ExternalReference",
                  "keys": [
                    {
                      "type": "GlobalReference",
                      "value": "https://admin-shell.io/idta/TimeSeries/Timespan/1/1"
                    }
                  ]
                },
                "valueType": "xs:dateTime",
                "min": "",
                "max": "",
                "modelType": "Range"
              }
´´´

**Comment by zrgt** [comment]
Also a problem in `ExternalReference` in `semantiid` of segments. According to Constraint AASd-122 the type of the first key of an ExternalReference must be a GenericGloballyIdentifiable, but "Property" was set:
```json
            {
              "value": {
                "idShort": "Segments",
                "semanticId": {
                  "type": "ExternalReference",
                  "keys": [
                    {
                      "type": "Property",
                      "value": "https://admin-shell.io/idta/TimeSeries/AggregationMethod/1/1"
                    }
                  ]
                },
                "modelType": "SubmodelElementCollection"
              }
            }

**Comment by Rudra-sandeep** [comment]
@zrgt Thank you for your feedback I will look into this issues.

**Comment by zrgt** [comment]
@Rudra-sandeep the same problems mentioned in the original issue report also appear in JSON.

**Comment by zrgt** [comment]
> @zrgt Thank you for your feedback, I will look into this issue.

@Rudra-sandeep Please consider that probably all issues mentioned in this problem also exist in all JSON files that have been uploaded recently.

**Comment by Rudra-sandeep** [comment]
> > @zrgt Thank you for your feedback, I will look into this issue.
> 
> @Rudra-sandeep Please consider that probably all issues mentioned in this problem also exist in all JSON files that have been uploaded recently and the Serializer/SDK you are using is not compliant with the AAS Spec.

@zrgt Yes regarding to compliant with the Spec we have already started discussions in the WG's

**Comment by Rudra-sandeep** [comment]
@zrgt Thank you for raising the issue and the issue is been solved you can find the Bugfixed SMT at below link
[https://github.com/admin-shell-io/submodel-templates]
