### ISSUE TITLE
SMT CarbonFootptint (IDTA 2023-0-9) could not be loaded into AASPE

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/submodel-templates#69]
The AASX-File of the Template has been updated April 30, 2024. Since then it can not be loaded into the Package Explorer (Version v2024-06-10)

_Error:  375 gave: While opening the package to read AASX C:\Users\RIS\AppData\Local\Temp\tmp5AA9.aasx at \AdminShellPackageEnv.cs:line 366 gave: End of Central Directory record could not be found.)_

**Comment by Rudra-sandeep** [comment]
@foprs Please use the latest version of the AASPE tested both the AASX and JSON files they are working as intended.
