### ISSUE TITLE
Asset Data Manipulation

### ISSUE THREAD

**Issue by magnus-redeker** [admin-shell-io/submodel-templates#7]
**Submitter:** 
Magnus Redeker (Fraunhofer IOSB-INA)

**Target Users:** 
1. Machine Operator
2. Factory Manager
3. Autnomous Optimazion Service
4. etc.

**Description:**
1. The Target User connects to the AAS of the Asset of interest 
2. The Target User connects to the Asset Interface Description Submodel describing which operation modes (semanticId) of the Asset can be selected through which interfaces with which security requirements
3. The Target User selects an operation mode for the asset
4. The Target User configures a client of the relevant Asset interface fullfilling the security requirements
-for example: client for Asset's OPC UA server with Namespace and NodeID
5. The Target User deploys the configured client that connects to the Asset interface and changes the Asset's operation mode

**Technologies of interest:**
1. HTTPS/REST
2. MQTT 
3. Apache Kafka
4. OPC UA: Standard, PubSub, ReverseConnect
5. ProfiBus
6. ProfiNet
7. ModBus
8. etc.

**Gaps:**
Currently, no "omniscient" register like the Asset Interface Description exists

**Links:** 
None

**Comment by SAidta** [comment]
The use case was discussed within the working group.
