### ISSUE TITLE
Carbon Footprint SMT descriptions are abbreviated

### ISSUE THREAD

**Issue by empwilli** [admin-shell-io/submodel-templates#78]
In the most recent version of the Carbon Footprint the description elements are abbreviated, e.g, for the CarbonFootprint submodel it is "The Submodel provides the means to access the Carbon Footprint …", whereas this description in earlier versions (until 7e9d19c9143ac725973859d2b5c0e2a01a7d792a) reads "The Submodel provides the means to access the Carbon Footprint of the asset."  

The same problem is true for the remaining descripions. As far as I can see the last fine version is 7e9d19c9143ac725973859d2b5c0e2a01a7d792a.

**Comment by Rudra-sandeep** [comment]
@empwilli Thank you for the feedback It was done due the AAS-constrain related to description but now the issue is solved in the latest version.
