### ISSUE TITLE
Device & Datapoint Onboarding

### ISSUE THREAD

**Issue by sebastiankb** [admin-shell-io/submodel-templates#8]
**Submitter:** 
Sebastian Käbisch (Siemens)

**Target Users:** 

- system & backend integrator
- software developer
- engineers
- ... 

**Description:**

1. Engineer wants to import different sensor measurements from energy meters of different vendors into a backend system to monitor energy data of a plant system 
2. Each energy meter may support different protocols (e.g., Modbus, Profibus, HTTP) and data model representation
3. Depending of industry sector and supported protocol, energy meters may have a protocol electronic device / interface description exists such as EDDL that can be used for onboarding
4. However, if such electronic description not exists typically the communication & datapoint metadata is retrieved in manuals (PDF, webpages, ...) or tables (CVS, Excel,...)
5.  Taking over such information in application or engineering development is an expensive process (e.g., c&p over 80 datapoint of a single device) and causes risk of error proneness (e.g., wrong calculation or interpretation of communication metadata)
 
**Gaps:**

- single place to get details about the interface description 
- some devices come with existing device description solutions such as EDDL, and some do not have it. There is the need that both situations can be reflected  
- semantic context / meaning of the data 

**Links:**
link to presentation [here](https://industrialdigitaltwin.sharepoint.com/:b:/r/sites/IDTAIndustrialDigitalTwinAssociatione.V/Freigegebene%20Dokumente/WG2%20-%20Submodels/Submodel-Development/Asset%20Interface%20Description/20%20Design/Meeting%202022-03-15/2022_SMT_AID_UseCase_Onboarding.pdf?csf=1&web=1&e=Qihk2K) (requires access to IDTA sharepoint)

**Comment by SAidta** [comment]
The use case was discussed within the working group.
