### ISSUE TITLE
Timeseries submodel unable to fetch data from Influx-Linked Segment

### ISSUE THREAD

**Issue by ankitgaur0212** [admin-shell-io/submodel-templates#83]
Hello Everyone,

I recently started with building and using AAS Shell. So in my usecase - I am trying to integarte my Machine with AAS using Timeseries Submodel. We already have MQTT broker setup.
**infra is on Docker.**
- aas web ui- 202410 version
- aas registry
- aas submodel registry
- aas repo
- submodel repo
- mosquitto
- telegraf
- dashboard api
- aasx server
- influxdb
- Mongo
I will also attach the screenshot for reference.
So i have build a AAS Shell for Timeseries and i am trying to use  linked Segment which will pick data from Influx based on the parameters.
i have passed the endpoint details and a valid query(i run the query on influx and it is getting  me the data) in the SME and in visulaization when i am selecting Segment and X and Y parameters and click on FETCH DATA. it shows nothing. Nothing on the graph as well.
However i have checked the same query in influx and it is fetching data.
i also tried with older version of AAS WEB UI (202403) and it worked fine, however with the new version (202410) i do not see and data is being fetched.
is i am doing anything wrong ? or i missing any part? Need assistance here.

Thanks
![image](https://github.com/user-attachments/assets/6c8e3a5f-0b5f-4897-84c9-f952154288a2)

**AAS UI Images**
Linked segment
![image](https://github.com/user-attachments/assets/c94f180a-a321-4629-b776-4008fd217adc)
![image](https://github.com/user-attachments/assets/2616921c-fc1f-4d07-a24a-32e21c12cbe7)

![image](https://github.com/user-attachments/assets/01b638f7-9f9a-4381-ad9a-9c563946d3bc)

**Comment by Rudra-sandeep** [comment]
@ankitgaur0212 Please raise the issue here [https://github.com/eclipse-basyx/basyx-aas-web-ui](url) as this issue is not related to the SMT Timeseries submodel
