### ISSUE TITLE
WIP: Semantic Integration & Representation

### ISSUE THREAD

**Issue by sebastiankb** [admin-shell-io/submodel-templates#9]
**Please note this use case is still in wip.**

**Submitter:** 
Sebastian Käbisch (Siemens)

**Target Users:** 

- system & backend integrator
- software developer
- ... 

**Description:**

1. An application like to use a specific datapoint of an asset (e.g, power at phase I of an energy meter)
2. Typically it is important to know the specific (parameter/variable) name of the datapoint and semantic context (e.g.,  unit, phase location, etc.)
3. ... 
 
**Gaps:**
- semantic context / meaning of the data 

**Links:**

**Comment by SAidta** [comment]
The use case was discussed within the working group.
